-- MySQL Script generated by MySQL Workbench
-- 08/23/16 13:16:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stok_barang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stok_barang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stok_barang` DEFAULT CHARACTER SET utf8 ;
USE `stok_barang` ;

-- -----------------------------------------------------
-- Table `stok_barang`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stok_barang`.`barang` (
  `idbarang` INT NULL AUTO_INCREMENT,
  `nama_barang` VARCHAR(45) NULL,
  `jenis_barang` VARCHAR(45) NULL,
  `stok_barang` INT NULL,
  PRIMARY KEY (`idbarang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stok_barang`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stok_barang`.`history` (
  `idhistory` INT NULL AUTO_INCREMENT,
  `waktu` VARCHAR(75) NULL,
  `jenis_barang` VARCHAR(45) NULL,
  `nama_barang` VARCHAR(45) NULL,
  `kegiatan` LONGTEXT NULL,
  PRIMARY KEY (`idhistory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stok_barang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stok_barang`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `stok_barang`.`user` (`user_id`, `username`, `password`) VALUES (NULL, 'admin', 'admin');